### ISSUE TITLE
Not work on webpack 1.12.2

### ISSUE THREAD

**Issue by jilen** [mzgoddard/hard-source-webpack-plugin#304]
Webpack 1.12.2
```
 building for production...(node:17289) UnhandledPromiseRejectionWarning: TypeError: compilation.dependencyFactories.keys is not a function
    at Compiler.pluginCompat.tap.compilation (/home/jilen/Workspace/wx-member/client/node_modules/hard-source-webpack-plugin/lib/hard-basic-dependency-plugin.js:380:60)
```

**Comment by vasconita** [comment]
Same here :raised_hand:

Webpack version: 1.12.14

**Comment by jilen** [comment]
I am using the latest version from npm

**Comment by piecyk** [comment]
Hard say what is going there... more information like your webpack config would help.

**Comment by Venryx** [comment]
I'm getting the same error, in Webpack 4, for my project: https://github.com/Venryx/js-vextensions

```
[hard-source:core] HardSourceWebpackPlugin is writing to a new confighash path for the first time: C:\Root\Apps\@V\@Modules\js-vextensions\Main\node_modules\.cache\hard-source\82d0126f3e26927fad6228db7e0c5a301c5d8c14a0d37acbd56f689dcb804995
  0% compile(node:2264) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: compilation.dependencyFactories.keys is not a function
```

**Comment by mzgoddard** [comment]
Try `hard-source-webpack-plugin@0.5``0.6` and after have dropped webpack 1 support.

**Comment by mzgoddard** [comment]
`0.7` will be dropping webpack 2 and node 6 support.
